# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0002_auto_20170929_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('pub_time', models.DateTimeField()),
                ('shortcode', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ins_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ins_block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('pub_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'ins_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ins_friend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('eamil', models.CharField(blank=True, max_length=254, null=True)),
                ('about_self', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.IntegerField()),
                ('is_private', models.IntegerField()),
                ('is_verified', models.IntegerField()),
            ],
            options={
                'db_table': 'ins_user',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='block',
            name='people',
        ),
        migrations.RemoveField(
            model_name='block',
            name='target',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='people',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='target',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
