# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0004_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.InsArticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.InsUser')),
            ],
        ),
    ]
