# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0005_inslike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inslike',
            options={'managed': False},
        ),
    ]
