# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0006_auto_20171003_1717'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inslike',
            table='ins_like',
        ),
    ]
