# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0008_inssign'),
    ]

    operations = [
        migrations.AddField(
            model_name='inssign',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
    ]
