# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-11 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0012_inssign_has_read'),
    ]

    operations = [
    ]
