# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-11 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0014_auto_20171011_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(null=True)),
                ('has_read', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_article', to='ins.InsArticle')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_people', to='ins.InsUser')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_target', to='ins.InsUser')),
            ],
            options={
                'db_table': 'ins_sign',
            },
        ),
    ]
